
[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 1
blur = false

[window.padding]
x = 10
y = 10

[font]
size = 19

[font.normal]
family = "FiraCode Nerd Font Propo"

[font.bold]
family = "FiraCode Nerd Font Propo"

[font.italic]
family = "FiraCode Nerd Font Propo"

[keyboard]

[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\b"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Plus"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[general]
import = ["/Users/jan/.config/alacritty/themes/autumn.toml"]
